// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "Event/EventSystem.h"

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "LightSwitchActor.generated.h"

UCLASS()
class YETANOTHEREVENT_API ALightSwitchActor : public AActor
{
	GENERATED_BODY()
	
public:	
	ALightSwitchActor();

protected:
	virtual void Tick(float DeltaTime) override;

private:
	void TurnOnLight();

	UPROPERTY(EditAnywhere, Category = "Own|Light Switch")
	float LightIntensity{ 200.0f };

	UPROPERTY(EditInstanceOnly, Category = "Own|Light Switch")
	TObjectPtr<class AGameplayLightActor> AttachedLight{ nullptr };

public:
	UEVENT(ParamNames = ("Amount", "Score", "Health", "PlayerLocation"))
	TEvent<int64, int32, int, FVector, bool> OnLightSwitchToggled_New_Two{};


	bool bTriggeredOnce{};

	// YAE_GENERATED_CODE_BEGIN
	#pragma region UEVENT Generated Code (DO NOT TOUCH!)
	// Generated by YetAnotherEventCodegen C#. Do not edit this region by hand.
	// Re-run the generator after changing UEVENT declarations.

	#pragma region Generated Blueprint Delegate for OnLightSwitchToggled_New_Two
	public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_FiveParams(FOnLightSwitchToggled_New_TwoBP, int64, Amount, int32, Score, int, Health, FVector, PlayerLocation, bool, Param5);
	UPROPERTY(BlueprintAssignable, Category = "Events")
	FOnLightSwitchToggled_New_TwoBP OnLightSwitchToggled_New_Two_BP;
	private:
	uint8 _AutoBind_OnLightSwitchToggled_New_Two = [this]() -> uint8 {
		OnLightSwitchToggled_New_Two.SubscribeLambda(this, [this](auto&&... args) {
			OnLightSwitchToggled_New_Two_BP.Broadcast(Forward<decltype(args)>(args)...);
		});
		return 0;
	}();
	public:
	#pragma endregion
	private:
	#pragma endregion
	// YAE_GENERATED_CODE_END
};











