// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "GlobalEventGate.h"
#include "GlobalEventPayload.h"
#include "Event/EventSystem.h"
#include "GameplayTagContainer.h"

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "GlobalEventListenerComponent.generated.h"

USTRUCT(BlueprintType)
struct FThresholdValue {
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, meta = (ClampMin = "1"), Category = "Global Events|Gate")
    int32 Value = 1;
};

UCLASS(ClassGroup = (Custom), meta = (BlueprintSpawnableComponent))
class YETANOTHEREVENTRUNTIME_API UGlobalEventListenerComponent : public UActorComponent {
	GENERATED_BODY()

public:
	UGlobalEventListenerComponent();

protected:
	virtual void BeginPlay() override;
	virtual void EndPlay(EEndPlayReason::Type EndPlayReason) override;
	virtual void TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) override;

public:
	UFUNCTION(BlueprintPure, Category = "Global Events|Listener")
	bool UsesGate() const;

public:
	UEVENT(ParamNames = ("GlobalEventPayload"))
	TEvent<const FGlobalEventPayload&> OnReceivedGlobalEvent{};

	UEVENT()
	TEvent<> OnPassedGlobalEventGate{};

	UEVENT(BlueprintCallable, ParamNames = ("GlobalEventPayload"))
	TEvent<const FGlobalEventPayload&> OnReceivedGlobalEvent_Two{};

private:
	// The event tags this component should subscribe to.
	UPROPERTY(EditAnywhere, Category = "Global Events|Listener")
	FGameplayTagContainer EventsToListenFor{};

	// Optional. If empty, this listener accepts events from all channels.
	UPROPERTY(EditAnywhere, Category = "Global Events|Listener")
	FGameplayTagContainer Channels{};

	// Optional advanced gate. This is evaluated against received listener tags.
	UPROPERTY(EditAnywhere, Category = "Global Events|Gate")
	FGlobalEventGate GlobalEventGate{};

	UPROPERTY(EditAnywhere, Category = "Global Events|Gate")
	bool bResetGateWhenPassed{true};

	// Optional. Counts unique senders per listened event tag before the tag is considered received by the gate.
	UPROPERTY(EditAnywhere, Category = "Global Events|Gate")
	TMap<FGameplayTag, FThresholdValue> TagThresholds{};

	TMap<FGameplayTag, TSet<TWeakObjectPtr<UObject>>> SenderAccumulator{};

	FGameplayTagContainer ReceivedEvents{};

	TMap<FGameplayTag, FEventHandle> ActiveHandles{};

	void HandleGlobalEvent(const FGlobalEventPayload& Payload, FGameplayTag MatchedSubscriptionTag);
	bool PassesChannelFilter(const FGlobalEventPayload& Payload) const;
	void AccumulateGateEvent(const FGlobalEventPayload& Payload, FGameplayTag MatchedSubscriptionTag);
	void ResetGateState();

	// YAE_GENERATED_CODE_BEGIN
	#pragma region UEVENT Generated Code (DO NOT TOUCH!)
	// Generated by YetAnotherEventCodegen C#. Do not edit this region by hand.
	// Re-run the generator after changing UEVENT declarations.

	#pragma region Generated Blueprint Delegate for OnReceivedGlobalEvent
	public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnReceivedGlobalEventBP, const FGlobalEventPayload&, GlobalEventPayload);
	UPROPERTY(BlueprintAssignable, Category = "Events")
	FOnReceivedGlobalEventBP OnReceivedGlobalEvent_BP;
	private:
	uint8 _AutoBind_OnReceivedGlobalEvent = [this]() -> uint8 {
		OnReceivedGlobalEvent.SubscribeLambda(this, [this](auto&&... args) {
			OnReceivedGlobalEvent_BP.Broadcast(Forward<decltype(args)>(args)...);
		});
		return 0;
	}();
	public:
	#pragma endregion

	#pragma region Generated Blueprint Delegate for OnPassedGlobalEventGate
	public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE(FOnPassedGlobalEventGateBP);
	UPROPERTY(BlueprintAssignable, Category = "Events")
	FOnPassedGlobalEventGateBP OnPassedGlobalEventGate_BP;
	private:
	uint8 _AutoBind_OnPassedGlobalEventGate = [this]() -> uint8 {
		OnPassedGlobalEventGate.SubscribeLambda(this, [this](auto&&... args) {
			OnPassedGlobalEventGate_BP.Broadcast(Forward<decltype(args)>(args)...);
		});
		return 0;
	}();
	public:
	#pragma endregion

	#pragma region Generated Blueprint Delegate for OnReceivedGlobalEvent_Two
	public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnReceivedGlobalEvent_TwoBP, const FGlobalEventPayload&, GlobalEventPayload);
	UPROPERTY(BlueprintAssignable, Category = "Events")
	FOnReceivedGlobalEvent_TwoBP OnReceivedGlobalEvent_Two_BP;
	private:
	uint8 _AutoBind_OnReceivedGlobalEvent_Two = [this]() -> uint8 {
		OnReceivedGlobalEvent_Two.SubscribeLambda(this, [this](auto&&... args) {
			OnReceivedGlobalEvent_Two_BP.Broadcast(Forward<decltype(args)>(args)...);
		});
		return 0;
	}();
	public:

	// Auto-generated Blueprint broadcast wrappers.
	UFUNCTION(BlueprintCallable, Category = "Events|OnReceivedGlobalEvent_Two", meta = (DisplayName = "Broadcast OnReceivedGlobalEvent_Two"))
	void BP_Broadcast_OnReceivedGlobalEvent_Two(const FGlobalEventPayload& GlobalEventPayload) {
		OnReceivedGlobalEvent_Two.Broadcast(GlobalEventPayload);
	}

	UFUNCTION(BlueprintCallable, Category = "Events|OnReceivedGlobalEvent_Two", meta = (DisplayName = "Sliced Broadcast OnReceivedGlobalEvent_Two", AdvancedDisplay = "MaxExecutionsPerFrame"))
	void BP_SlicedBroadcast_OnReceivedGlobalEvent_Two(const FGlobalEventPayload& GlobalEventPayload, int32 MaxExecutionsPerFrame = 10) {
		OnReceivedGlobalEvent_Two.SlicedBroadcast(MaxExecutionsPerFrame, GlobalEventPayload);
	}
	#pragma endregion
	private:
	#pragma endregion
	// YAE_GENERATED_CODE_END
};
