// Copyright (c) 2026 Core Memory Entertainment GbR. All rights reserved.

#pragma once

#include "Event/EventSystem.h"

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "GameplayTagContainer.h"
#include "StructUtils/InstancedStruct.h"
#include "GlobalEventBroadcasterComponent.generated.h"

USTRUCT(BlueprintType)
struct FGlobalEventBroadcastEntry {
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Global Events|Broadcast")
	FGameplayTag EventTag{};

	// Optional. If empty, the event is broadcast once without a channel.
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Global Events|Broadcast")
	FGameplayTagContainer Channels{};

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Global Events|Broadcast")
	FInstancedStruct PayloadData{};

	// When true, listeners subscribed to parent tags can also receive this event.
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Global Events|Broadcast|Advanced")
	bool bPropagateToParents = true;
};

UCLASS(ClassGroup = (Custom), meta = (BlueprintSpawnableComponent))
class YETANOTHEREVENTRUNTIME_API UGlobalEventBroadcasterComponent : public UActorComponent {
	GENERATED_BODY()

public:
	UGlobalEventBroadcasterComponent();

protected:
	virtual void BeginPlay() override;
	virtual void TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) override;

public:
	UEVENT(ParamNames = ("BroadcastedPayload"))
	TEvent<const FGlobalEventPayload&> OnGlobalEventBroadcastRequested{};

	UFUNCTION(BlueprintCallable, Category = "Global Events|Broadcaster")
	void TriggerEvents();

private:
	void BroadcastEntry(const FGlobalEventBroadcastEntry& Entry, UObject* SenderObject);

private:
	// Each entry can have its own event tag, channels, payload, and propagation behavior.
	UPROPERTY(EditInstanceOnly, Category = "Global Events|Broadcaster", meta = (TitleProperty = "EventTag"))
	TArray<FGlobalEventBroadcastEntry> EventsToBroadcast{};

	// YAE_GENERATED_CODE_BEGIN
	#pragma region UEVENT Generated Code (DO NOT TOUCH!)
	// Generated by YetAnotherEventCodegen C#. Do not edit this region by hand.
	// Re-run the generator after changing UEVENT declarations.

	#pragma region Generated Blueprint Delegate for OnGlobalEventBroadcastRequested
	public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnGlobalEventBroadcastRequestedBP, const FGlobalEventPayload&, BroadcastedPayload);
	UPROPERTY(BlueprintAssignable, Category = "Events")
	FOnGlobalEventBroadcastRequestedBP OnGlobalEventBroadcastRequested_BP;
	private:
	uint8 _AutoBind_OnGlobalEventBroadcastRequested = [this]() -> uint8 {
		OnGlobalEventBroadcastRequested.SubscribeLambda(this, [this](auto&&... args) {
			OnGlobalEventBroadcastRequested_BP.Broadcast(Forward<decltype(args)>(args)...);
		});
		return 0;
	}();
	public:
	#pragma endregion
	private:
	#pragma endregion
	// YAE_GENERATED_CODE_END
};
