;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Events.LightOff",NewTagName="Events.PlateLeft")
+GameplayTagRedirects=(OldTagName="Events.LightOn",NewTagName="Events.PlaneCenter")
+GameplayTagRedirects=(OldTagName="Events.PlaneCenter",NewTagName="Events.PlateCenter")
+GameplayTagRedirects=(OldTagName="Events.PlateLeft",NewTagName="Events.Command.Activate")
+GameplayTagList=(Tag="Channels",DevComment="")
+GameplayTagList=(Tag="Channels.Puzzle",DevComment="")
+GameplayTagList=(Tag="Channels.Puzzle.Room1",DevComment="")
+GameplayTagList=(Tag="Channels.Puzzle.Room1.A",DevComment="")
+GameplayTagList=(Tag="Channels.Puzzle.Room1.B",DevComment="")
+GameplayTagList=(Tag="Channels.Puzzle.Room1.C",DevComment="")
+GameplayTagList=(Tag="Events.Command.Activate",DevComment="")

